### ISSUE TITLE
A way to not tone down punctuation and brackets using stylesheet? 

### ISSUE THREAD

**Issue by montykamath** [simurai/duotone-syntax#29]
Is there a way to override something styles.less to not tone down punctuation and brackets and less important things?  Would like to use for coding so punctuation is still pretty important.  Thanks!

**Comment by simurai** [comment]
Yeah, you could try to override it in your styles.less file like:

```less
.syntax--punctuation.syntax--punctuation.syntax--punctuation.syntax--punctuation,
.syntax--bracket,
.syntax--brace {
  color: hsl(240, 8%, 48%);
}
```

![image](https://user-images.githubusercontent.com/378023/37389330-3f6a6d9e-27a7-11e8-8045-1101188ec473.png)

Although hiding punctuation in this theme is intentional. It's not for everyone's taste, though.
