### ISSUE TITLE
Italicize comments

### ISSUE THREAD

**Issue by maxlapides** [simurai/duotone-syntax#3]
Hi there! Love the work you've done on Duotone -- it looks awesome! I was just wondering what your thoughts are on italicizing code comments. (I personally prefer my syntax highlighting scheme to italicize code comments.) Thanks again :)

**Comment by huphtur** [comment]
+1

**Comment by simurai** [comment]
:+1:  Yeah, I like it too. Let's do it.

If somebody really hates it, it can be undone in `styles.less` with

``` css
atom-text-editor::shadow .comment {
  font-style: normal;
}
```
